### ISSUE TITLE
Troubles with Get-ADUser

### ISSUE THREAD

**Issue by fflaten** [Jawz84/explainpowershell#38]
Analyzing `Get-aduser -Filter { $_.SamAccountName -like '*demo*' -and $_.PasswordNeverExpires -eq $true }` throws an unhandled exception.

_I know it is invalid filter syntax for Get-ADUser, it's just a demo. The real one, `Get-aduser -Filter { SamAccountName -like '*demo*' -and PasswordNeverExpires -eq $true }`, has other problems. Properties inside filter aren't detected, but that's ActiveDirectory-module specific syntax so it's a different issue._ 🙂

**Comment by Jawz84** [comment]
Thanks for reporting @fflaten !
I can reproduce it, so that's a nice start. 
And if I add parentheses around the operands for the -and operator it does work, if I leave them out, it fails. I'm going to add a test with your sample code and investigate my code.

**Comment by fflaten** [comment]
Cool 👍

Congrats on launching a cool tool. I'm sure it will be useful for lots of users. 🎉

**Comment by Jawz84** [comment]
Thanks!

**Comment by Jawz84** [comment]
@fflaten I've fixed it :)
image](https://user-images.githubusercontent.com/26464885/121970175-3f7e2a00-cd76-11eb-9d00-389396252691.png)
