### ISSUE TITLE
Show multiple RelatedLinks as list

### ISSUE THREAD

**Issue by bravo-kernel** [Jawz84/explainpowershell#45]
It would be nice if the `RelatedLinks` section would list multiple entries as a (bulleted?) list instead of the current flat list.

![image](https://user-images.githubusercontent.com/230500/129611653-cab30d9a-9573-4b79-b8ac-60993d52b1e4.png)

**Comment by Jawz84** [comment]
Should be live in ~10 mins. [![Deploy app to Azure](https://github.com/Jawz84/explainpowershell/actions/workflows/deploy_app.yml/badge.svg)](https://github.com/Jawz84/explainpowershell/actions/workflows/deploy_app.yml)

**Comment by bravo-kernel** [comment]
Awesome, good luck with the project !

**Comment by Jawz84** [comment]
Thanks 👍
