### ISSUE TITLE
Parameter help is not shown, even though the help info is available in the database

### ISSUE THREAD

**Issue by Jawz84** [Jawz84/explainpowershell#64]
Just did a quick test with

```
Get-VM | Get-Stat -Stat 'cpu.usage.average' -Realtime
```

It looks as if the explanation for the parameters is not expanded, 

![image](https://user-images.githubusercontent.com/7760649/169004315-bbb51988-c071-4c6f-be54-7d9058786dd5.png)

although it is available in the help.

![image](https://user-images.githubusercontent.com/7760649/169004467-519ae1f5-2a0b-4c68-a291-be7690eb74c6.png)

_Originally posted by @lucdekens in https://github.com/Jawz84/explainpowershell/issues/63#issuecomment-1129772411_

**Comment by Jawz84** [comment]
I can reproduce this on production by running 'get-stat -realtime'.

I have confirmed that the intended data is available in the Azure DB with all the help info:
```json
(...)
{
    "Aliases": "none",
    "DefaultValue": "False",
    "Description": "Indicates whether the command collects real time statistics.",
    "Globbing": "false",
    "IsDynamic": false,
    "Name": "Realtime",
    "ParameterSets": {
      "__AllParameterSets": {
        "IsMandatory": false,
        "Position": -2147483648,
        "ValueFromPipeline": false,
        "ValueFromPipelineByPropertyName": false,
        "ValueFromRemainingArguments": false,
        "HelpMessage": null,
        "HelpMessageBaseName": null,
        "HelpMessageResourceId": null
      }
    },
    "PipelineInput": "False",
    "Position": "named",
    "Required": "false",
    "SwitchParameter": true,
    "TypeName": "SwitchParameter"
  },
(...)
``` 

[Relevant line of code](https://github.com/Jawz84/explainpowershell/blob/d595f429ea1dc2d7539063633d7cb367f1c3b3f0/explainpowershell.analysisservice/AstVisitorExplainer.cs#L287)

TODO: 
Reproduce locally so I can test.

**Comment by Jawz84** [comment]
Ok local repro succeeded. Log says:
```cli
[2022-05-18T09:54:05.007Z] PowerShell code sent: get-stat -realtime
[2022-05-18T09:54:05.038Z] Failed to get Description for parameter 'realtime' on command 'Get-Stat': The JSON value could not be converted to explainpowershell.models.ParameterTypeData. Path: $[0].TypeName | LineNumber: 24 | BytePositionInLine: 33.
```

**Comment by lucdekens** [comment]
It looks like those missing help lines are not exclusive for PowerCLI cmdlets.

The following example shows the same lack of help info for both parameters.

```
import-module -name test.module -allowclobber
```

![image](https://user-images.githubusercontent.com/7760649/169022189-c5e7f336-d768-4f69-ba62-75f6e40f09c2.png)

**Comment by Jawz84** [comment]
I was starting to suspect exactly this. The error says the json cannot be parsed to the target schema/type in C#. So I messed something up there.
Clearly a test should have been in place for this scenario. 
I am out of time and energy for today. Will continue later. Feel free to have a look at the code if you feel like that kind of thing.

**Comment by Jawz84** [comment]
It seems there there are two problems here: one is that for some cmdlets, the parameter help is so big, it doesn't fit the 64k limit in an Azure Table storage property. This is why `Import-Module -name` didn't return any help (-allowclobber is not a valid param here). So that part needs some work, because it means some module help imports may have failed because the Parameter property data was too big. It appears I can compress the json before uploading, and that saves quite a bit of space. This is what I did to fix this for Import-Module. But now I have to figure out a way to fix this at scale.

The other problem (where the parameter data does not fit the schema) I have not even touched yet.

**Comment by Jawz84** [comment]
TODO: find out why sometimes the stored parameter data does not fit the json schema to load them
