### ISSUE TITLE
Prevent modules from clobbering each others' cmdlets

### ISSUE THREAD

**Issue by Jawz84** [Jawz84/explainpowershell#71]
If one module has a 'get-vm' cmdlet, and another one does as well, the second may overwrite the first in the helpdb.

**Comment by Jawz84** [comment]
Fixed now:
![image](https://user-images.githubusercontent.com/26464885/174783213-90a19bfe-b67d-42d4-9064-3f356f5c364e.png)
@lucdekens, for your info and pleasure. VMware and Hyper-v module help is now available side-by-side

**Comment by lucdekens** [comment]
Great.
Note there are other conflicting cmdlets like Get-VMHost, Move-VM, New-VM, Restart-VM, Remove-VM, Set-VMHost, ...

The fact that you list the conflicting modules makes it easy to update the code.

Good fix!
