### ISSUE TITLE
Call operator are not supported

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#75]
Try 
```
. {dir}
& {dir}
```
The previous cache is not cleared is this case.

**Comment by Jawz84** [comment]
I think I understand what you mean.
Repro steps:

Explain something valid, and then try to explain `.{}` or `& {}`. The previous explanation will be shown again, together with an error.
![Screenshot_20220626-131757_Edge.jpg](https://user-images.githubusercontent.com/26464885/175811632-b4021611-aea2-4d0f-86a1-39716f28830c.jpg)

**Comment by Jawz84** [comment]
@LaurentDardenne thanks for letting me know. I fixed it. [Deploy is running](https://github.com/Jawz84/explainpowershell/actions/runs/2564193925), should be ready in under 10mins.
