### ISSUE TITLE
Generic types are not properly handled

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#77]
Examples :
```powershell
$names=[System.Collections.Generic.List[String]]::New()
{} -as [System.Action[String,int]] #only the operator is known not the operands
(${function:Print} -as [System.Action[String]])
[System.Action[String]]
{} -as [System.Action[String,int]]
```
That said, Bravo . Because Powershell code analysis is difficult

**Comment by Jawz84** [comment]
Thanks, I see. I think I can improve explanation for type conversion operators, mention the right hand side operand. 
The (generict) types themselves are handled OK I think.

**Comment by LaurentDardenne** [comment]
_>>The (generic) types themselves are handled OK I think._
Ok.
I may be confusing the term 'oneliner' with a simple statement.
In the following example:
```
$D=[datetime] ; $G=[System.Action[String]]
```
www.explainpowershell.com does not indicate that I am handling a generic class in the second assignment. Which in my opinion is important to specify if you want to explain to a beginner the submitted code.

**Comment by Jawz84** [comment]
I just want to say I really appreciate your feedback! Merci beaucoup 👍

**Comment by Jawz84** [comment]
> In the following example:
> 
> ```
> $D=[datetime] ; $G=[System.Action[String]]
> ```
> 
> [www.explainpowershell.com](http://www.explainpowershell.com) does not indicate that I am handling a generic class in the second assignment. Which in my opinion is important to specify if you want to explain to a beginner the submitted code.

I see what you mean. Types in the PowerShell Abstract syntax tree are a bit verbose, so I suppressed some parts. Which leads to omissions like this. I re-added this explanation to the case of AssignmentStatementAst now.

**Comment by Jawz84** [comment]
I'm also going to improve the help for the '-as' operators, and all operators like it.
