### ISSUE TITLE
The explanation is identical for two pipeline chain operators

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#82]
With : 
```Powershell
dir||Cls ; dir&&Cls
```
Result  : 
![image](https://user-images.githubusercontent.com/4894452/176892248-d43c5f31-6242-4796-a83f-9e9260dc6803.png)

According to this [documentation](https://docs.microsoft.com/en-us/powershell/module/microsoft.powershell.core/about/about_Pipeline_Chain_Operators?view=powershell-7.2#long-description) : 
_The && operator executes the right-hand pipeline, if the left-hand pipeline succeeded.
Conversely, the || operator executes the right-hand pipeline if the left-hand pipeline failed._

**Comment by Jawz84** [comment]
A great catch! This can be fixed here:

https://github.com/Jawz84/explainpowershell/blob/9b2a3447dc952a9d102c02e27071e0bec6d259f6/explainpowershell.analysisservice/AstVisitorExplainer.cs#L1181-1194

If you like, you are more than welcome to provide a pull request for this.
