### ISSUE TITLE
The explanation of the range operator seem not correct

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#85]
With
```Powershell
$T=(1..5),(6..10)
```
![image](https://user-images.githubusercontent.com/4894452/176915224-f2c40649-0b48-46b3-ad5f-13debffb6d58.png)

I dont understand : _The range operator '..'. This works from left to right, so targeting '10'_ 

Note, since PS v6:
```Powershell
"A".."Z"
```
_The range operator '..'. This works from left to right, so targeting '"Z"'_

**Comment by Jawz84** [comment]
Oof I agree, this looks ugly. I introduced this myself in #79, while working on #78 and #77.

Maybe we should change this here:
https://github.com/Jawz84/explainpowershell/blob/9b2a3447dc952a9d102c02e27071e0bec6d259f6/explainpowershell.analysisservice/codegen/TokenKind.csv#L48

And adapt the code here:
https://github.com/Jawz84/explainpowershell/blob/9b2a3447dc952a9d102c02e27071e0bec6d259f6/explainpowershell.analysisservice/AstVisitorExplainer.cs#L198-L214
