### ISSUE TITLE
The catch statement does not specify the type of associated exception

### ISSUE THREAD

**Issue by LaurentDardenne** [Jawz84/explainpowershell#88]
With
```Powershell
catch [System.Management.Automation.CommandNotFoundException] {"Command error trapped"};catch  {"Command error trapped"}
```
![image](https://user-images.githubusercontent.com/4894452/176928440-a62b4d9e-4498-439e-b1b4-77c700d86c27.png)

While the Trap statement considers the type of the exception
```Powershell
trap [System.Management.Automation.CommandNotFoundException] {"Command error trapped"}
```
![image](https://user-images.githubusercontent.com/4894452/176928794-a3205fbe-67ea-4dcb-ad44-59030797f899.png)

But in this case it is a value (a type) and not a constraint

**Comment by Jawz84** [comment]
`Trap`does not have an explanation in code yet, but `try {}; catch {}` does, I think I may have changed the behaviour there, or, possibly the type constraint is handled differently in the Ast there. 
Good one. Needs further attention
